sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pagani123/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pagani123/docker-react npm run test
